---
- name: List AWS S3 Buckets
  hosts: localhost
  gather_facts: no
  tasks:

  - name: List S3 Buckets
    community.aws.s3_bucket_info:
      validate_certs: False
    register: result

  - name: Display Bucket Names
    debug:
      var: result

  - name: Get Details of Each Bucket
    community.aws.s3_bucket_facts:
      name: "{{ item.name }}"
      validate_certs: False
    loop: "{{ result.buckets }}"
    register: bucket_details

  - name: Display Bucket Details
    debug:
      var: bucket_details.results
