---
- name: Create a simple S3 bucke
  hosts: localhost
  tasks:
    - name: create s3 01
      amazon.aws.s3_bucket:
        name: mys3bucket01
        state: present

    - name: create s3 02
      amazon.aws.s3_bucket:
        name: mys3bucket02
        state: present

    - name: create s3 03
      amazon.aws.s3_bucket:
        name: mys3bucket03
        state: present
