---
- name: Collect Windows System Information
  hosts: windows_hosts
  gather_facts: yes  # Gather facts about the target host

  tasks:
    - name: Display Hostname
      debug:
        var: ansible_hostname

    - name: Display IP Address
      debug:
        var: ansible_default_ipv4.address

    - name: Display OS Version
      debug:
        var: ansible_distribution + " " + ansible_distribution_version

    - name: Display CPU Information
      debug:
        var: ansible_processor

    - name: Display Memory Information
      debug:
        var: ansible_memory_mb

    - name: Display Disk Information
      debug:
        var: ansible_mounts
